# Generated by Django 4.0.2 on 2022-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
