# Generated by Django 4.0.2 on 2022-02-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='point',
        ),
    ]
