# Generated by Django 4.0.2 on 2022-02-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_room_room_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_name",
        ),
    ]
