# Generated by Django 4.0.2 on 2022-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField(default=0)),
                ('history', models.CharField(max_length=255)),
                ('usage', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
