# Generated by Django 4.0.2 on 2022-03-01 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('point', models.IntegerField(default=0)),
                ('history', models.CharField(max_length=255)),
                ('usage', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
