# Generated by Django 4.0.2 on 2022-02-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("original_image", models.CharField(max_length=255)),
                ("nst_image", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
