# Generated by Django 4.0.2 on 2022-03-02 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='hate',
            field=models.ManyToManyField(related_name='hates', to=settings.AUTH_USER_MODEL),
        ),
    ]
